<a href="https://colab.research.google.com/github/techchandru/Week-tasks/blob/main/week_2__assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Variables and Data Types
# Write a Python program that swaps two numbers without using a third variable.
a=10
b=20
a,b=b,a
print("a:", a)
print("b:", b)

a: 20
b: 10


In [ ]:
# 2. Lists - Nested Lists
# You have a nested list:
# data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# a) Extract and print the middle element from the nested list.
# b) Flatten the list into a single list [1, 2, 3, 4, 5, 6, 7, 8, 9] without using loops.
data = [[1,2,3],[4,5,6],[7,8,9]]
print(data[1])
print(data[1][1])
singleList = data[0] + data[1] + data[2]
print(singleList)

[4, 5, 6]
5
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# 3. Tuples - Tuple Unpacking
# Given:
# values = (100, 200, 300)
# a) Unpack this tuple into three variables and print them.
# b) Swap the values without using a temporary variable.
values = (100,200,300,)
a,b,c = values
print("values")
print("a", a)
print("b:", b)
print("c:", c)
a, b, c = c, a, b
print("after swapping")
print("a:", a)
print("b:", b)
print("c:", c)


values
a 100
b: 200
c: 300
after swapping
a: 300
b: 100
c: 200


In [ ]:
# 4. Dictionary - Complex Keys
# Create a dictionary where:
# •	Keys are tuples representing (x, y) coordinates.
# •	Values are the sum of x and y.
# Example:
# { (1,2): 3, (3,4): 7, (5,6): 11 }
# Write a function to retrieve the sum for a given coordinate.
dict1 = {(1,2) : 3, (3,4) : 7, (5,6) : 11}
print(dict1)
x = int(input("Enter the x co-ordinate :"))
y = int(input("Enter the y co-ordinate :"))

def retreive_sum(a,b):
  for key,value in dict1.items():
    if(key ==(x,y)):
      print(value)

retreive_sum(x,y)

{(1, 2): 3, (3, 4): 7, (5, 6): 11}
Enter the x co-ordinate :3
Enter the y co-ordinate :4
7


In [ ]:
# 5. Functions - Nested Functions
# Write a function outer_function(a, b) that:
# • Contains an inner function to calculate a² + b².
# • Returns the result.
# Call outer_function(3, 4) and print the result.
# ________________________________________
def outer_function(a, b):
    def inner_function():
        return a**2 + b**2
    return inner_function()

print(outer_function(3, 4))

25


In [ ]:
# 6. Functions - Lambda & Map
# You are given a list:
# numbers = [1, 2, 3, 4, 5]
# Use a lambda function and map() to generate a list where each number is cubed.
# ________________________________________
numbers = [1, 2, 3, 4, 5]
cubed_numbers = list(map(lambda x: x**3, numbers))
print(cubed_numbers)

[1, 8, 27, 64, 125]


In [ ]:
#7. Functions - Recursion
# #Write a recursive function to
# #calculate the sum of digits of a given number.
# Example:
# Input: 1234
# Output: 10
# (1+2+3+4)##
def sum(n):
  if n == 0:
    return 0
  return n % 10 + sum(n // 10)

n = int(input("Enter the number :"))
print("Sum of digits : ",sum(n))

Enter the number :1234
Sum of digits :  10


In [ ]:
# 8. List Comprehensions
# Generate a list of all numbers between 1 and 100 that:
# •	Are divisible by 5
# •	But not by 3
# Use list comprehension.
# ________________________________________
result = [x for x in range(1, 101) if x % 5 == 0 and x % 3 != 0]
print(result)

[5, 10, 20, 25, 35, 40, 50, 55, 65, 70, 80, 85, 95, 100]


In [ ]:
# 9. Dictionary - Sorting by Values
# Given:
# scores = {"Alice": 90, "Bob": 85, "Eve": 92}
# Sort this dictionary by values in descending order and print the result.
# ________________________________________
scores = {"Alice": 90, "Bob": 85, "Eve": 92}
sorted_scores = dict(sorted(scores.items(), key=lambda item: item[1], reverse=True))
print(sorted_scores)

{'Eve': 92, 'Alice': 90, 'Bob': 85}


In [ ]:
# 10. Sets - Unique Characters
# Write a Python function that takes a string as input and returns:
# • A set of unique characters in the string.
# • The number of unique characters.
# Example:
# Input: "hello"
# Output: {'h', 'e', 'l', 'o'}, 4
# ________________________________________
def unique_characters(s):
    unique_chars = set(s)

    return unique_chars, len(unique_chars)

input_string = "hello"
unique_chars, count = unique_characters(input_string)

print(unique_chars, count)

{'e', 'h', 'o', 'l'} 4


In [ ]:
# 12. Dictionary - Reverse Key-Value Mapping
# Given a dictionary:
# data = {"A": 1, "B": 2, "C": 3}
# Write a program to swap keys and values:
# Output: {1: "A", 2: "B", 3: "C"}
# ________________________________________
data = {"A":1,"B":2,"C":3}
swapped_data = {j:i for i,j in data.items()}
print(swapped_data )

{1: 'A', 2: 'B', 3: 'C'}


In [ ]:
 # 13. Functions - Multiple Return Values
#Write a function that takes two numbers as input and returns:
# 1.	Their sum
# 2.	Their difference
# 3.	Their product
# 4.	Their quotient
# Print all four results
a=int(input("enter first value"));
b=int(input("enter second value"));
sum=a+b;
print("sum=",sum);
dif=a-b;
print("difference =", dif);
pro=a*b;
print("product =",pro);


enter first value2
enter second value3
sum= 5
difference = -1
product = 6


In [ ]:
# 14. List - Finding Second Largest Number
# Write a function to find the second largest number in a given list without using sort().
# Example:
# Input: [10, 20, 4, 45, 99]
# Output: 45
# ________________________________________

def second_largest(lst):
    first, second = float('-inf'), float('-inf')

    for num in lst:
        if num > first:
            second, first = first, num
        elif num > second and num != first:
            second = num

    return second if second != float('-inf') else None

# Example
numbers = [10, 20, 4, 45, 99]
print(second_largest(numbers))

45


In [ ]:
# 15. List - Pair Sum Problem
# Given a list of numbers and a target sum, find all pairs in the list that add up to the target.
# Example:
# Input: [2, 4, 3, 7, 1, 9], Target: 10
# Output: [(3, 7), (1, 9)]
# ________________________________________

def find_pairs(lst, target):
    pairs = []
    seen = set()

    for num in lst:
        complement = target - num
        if complement in seen:
            pairs.append((complement, num))
        seen.add(num)

    return pairs

# Example
numbers = [2, 4, 3, 7, 1, 9]
target = 10
print(find_pairs(numbers, target))

[(3, 7), (1, 9)]


In [ ]:
# 16. Pandas - Filtering DataFrame
# You are given the following Pandas DataFrame:
# import pandas as pd
# df = pd.DataFrame({
#     "Name": ["Alice", "Bob", "Charlie", "David"],
#     "Age": [24, 27, 22, 32],
#     "Score": [85, 90, 78, 88]
# })
# Write a one-liner to filter and display only rows where Age is greater than 25.
# ________________________________________
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
        "Age": [24, 27, 22, 32],
            "Score": [85, 90, 78, 88]
            })
            # print(df)
df1 = df[df['Age'] >= 25]
display(df1)

Name  Age  Score
1    Bob   27     90
3  David   32     88

In [6]:
# 17. Pandas - Group By Operation
# You have the following DataFrame:
# df = pd.DataFrame({
#     "Department": ["IT", "HR", "IT", "Finance", "HR"],
#     "Salary": [70000, 50000, 80000, 60000, 52000]
# })
# Write a Pandas command to calculate the average salary per department.
import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})

average_salary = df.groupby("Department")["Salary"].mean()
print(average_salary)



Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


In [7]:
# 18. NumPy - Create a 5x5 Matrix
# Write a program to create a 5x5 NumPy matrix where:
# •	The diagonal elements are 1
# •	All other elements are 0
# Example:
# Output:
# [[1 0 0 0 0]
#  [0 1 0 0 0]
#  [0 0 1 0 0]
#  [0 0 0 1 0]
#  [0 0 0 0 1]]
# ________________________________________

import numpy as np

# Create a 5x5 identity matrix
matrix = np.eye(5)

# Print the matrix
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
# 19. NumPy - Element-wise Operations
# Given two NumPy arrays:
# import numpy as np
# a = np.array([1, 2, 3, 4])
# b = np.array([10, 20, 30, 40])
# Perform element-wise:
# 1.	Addition
# 2.	Multiplication
# 3.	Power (a^b)
# Print the results.
# ________________________________________

import numpy as np

# Given arrays
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Element-wise operations
addition = a + b
multiplication = a * b
power = a ** b

# Print results
print("Addition:\n", addition)
print("Multiplication:\n", multiplication)
print("Power:\n", power)

Addition:
 [11 22 33 44]
Multiplication:
 [ 10  40  90 160]
Power:
 [              1         1048576 205891132094649               0]


In [9]:
# 20. NumPy - Find Index of Maximum Value
# Given:
# arr = np.array([10, 25, 39, 50, 19])
# Write a one-liner to find the index of the maximum value.
# ________________________________________
arr = np.array([10, 25, 39, 50, 19])
print(arr.argmax())

3
